# Generated by Django 3.2.5 on 2021-07-07 01:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recepie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recepie_image_file_path),
        ),
    ]
